import { Client, ClientOptions, LocalAuth, Message } from "whatsapp-web.js"
import qrcode from "qrcode-terminal"
import logger from "../utils/logger";

// the .consumer file will listen all event send by wa there is couple important event that we need to listen

// On this line const waNumber = ['62812123456', '62012223121']create an array to save the wa numbers that we need to use, and have emty object that later to save the clients so we can have multiple wa in our app. 
// const waNumbers = ['6281234567890', '6281234567891']
const waNumbers = ['62811334932']

const clients: Record<string, Client> = {}

// this code we set the configuration and instantiate the client for each wa number that we have and clients[waNumber] = client to save the client created to object we declare before with wa number as reference last we export clients so the client can be use by other logic in other file. and last we import the wa-message.consumer.ts in src/index.ts import “./wa-message/wa-message.consumer”.
waNumbers.forEach((waNumber) => {
  const clientConfig: ClientOptions = {
    authStrategy: new LocalAuth({
      clientId: waNumber
    })
  }

  const client = new Client(clientConfig)

  // this event trigger when the QR code generated by wa-web in this we need to display the qr code generated to terminal or to web. for this part we will generate to terminal.
  client.on('qr', (qr) => {
    qrcode.generate(qr, { small: true })
  })

  // this event trigger after we scan the qr code and our wa authenticate and can be use.
  client.on('authenticated', (session) => {
    logger.info(`Client ${waNumber} authenticated`)
  })

  client.on('ready', () => {
    logger.info(`Client ${waNumber} ready`)
  })

  // this event trigger when the client received message from the wa
  // on message this is event that we will listen an use the most because all off the logic will live here
  client.on('message', (message: Message) => {
    logger.info(`Client ${waNumber} received message: ${message.body}`)
    client.sendMessage(message.from, `You said: ${message.body}`)
  })

  clients[waNumber] = client

  client.initialize()

})

export default clients